# Generated by Django 2.2.4 on 2020-06-24 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam1_app', '0002_auto_20200624_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likers',
            new_name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='uploads',
        ),
        migrations.AddField(
            model_name='post',
            name='quote',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_uploader', to='exam1_app.User'),
        ),
    ]
